<a href="https://www.kaggle.com/code/noob2511/numpy-basics-notebook?scriptVersionId=189588802" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import numpy.ma as ma # for creation and handling masked array

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Create a numpy array
Creation of a numpy array can be done with np.array function.


In [2]:
array = np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


# Maksed Array
The masked array is the arrays that have invalid or missing entries. It can be created by using the masked_array function. It's use is to create a new array full of masked values.

In [3]:
a = np.array([1,2,3,4,-1])
b = ma.masked_array(a , mask = [0,0,0,0,-1])
print(b)

[1 2 3 4 --]


# Types of arrays:
1. 1 - D array : It is essentially a list of elements. It can contain either a single row or a single column. The shape of 1-D array is in `n,` where n is the number of elements. 
2. 2- D array : It is like a matrix or a table with rows and columns. It has a shape of `m,n` where `m` is the number of rows and `n` is the number of columns
3. 3-D array : 3-D array is a collection of 2-D array. It has a shape of `p,m,n`, where `p` is the number of 2-D arrays, `m` is the row number and `n` is the column number

In [4]:
#Creation of 1 - D array
array_1D = np.array([1,2,3,4,5])
print('1 D array : ', array_1D)
print(array_1D.shape)
print()

#Creation of 2 - D array

array_2D = np.array([[1,2],[3,4], [5,6]])
print('2 D array : ', array_2D)
print(array_2D.shape)
print()

#Creation of 3 - D array

array_3D = np.array([[[1,2],[3,4], [5,6],[7,8]]])
print('3 D array : ', array_3D)
print(array_3D.shape)
print()


1 D array :  [1 2 3 4 5]
(5,)

2 D array :  [[1 2]
 [3 4]
 [5 6]]
(3, 2)

3 D array :  [[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
(1, 4, 2)



# Accessing values of arrays
Accessing values in arrays is done in the same way as we do for list by providing indexes in the form of `array[n]`, where n represents the value of accesible index.

In [5]:
#Accessing values for 1-D array
element_1D = array_1D[2]
print('The element for 1-D array : ', element_1D)
print()

#Accessing values for 2-D array
element_2D = array_2D[2,0]
print('The element for 2-D array : ', element_2D)
print()

#Accessing values for 3-D array
element_3D = array_3D[0,0,0]
print('The element for 3-D array : ', element_3D)
print()

The element for 1-D array :  3

The element for 2-D array :  5

The element for 3-D array :  1



# Random function
Random function in numpy is used to create arrays filled with random values. There are 3 ways by which we can create a random array:
1. **By using rand function :** We can create a random array between `0 and 1` and it will consider floating point values and the range will be exclusive of `0 and 1`.
2. **By using randn function :** We can create a random array of any value normally and it can take positive and negative values as well. It will consider floating point values only.
3. **By using uniform function :** We can create a random uniform array by giving it a size as well as a range


In [6]:
#Example of rand function

array_1D = np.random.rand(5)
print('1-D array : ',array_1D)
print()

array_2D = np.random.rand(2,2)
print('2-D array : ',array_2D)
print()
array_3D = np.random.rand(2,3,4)
print('3-D array : ',array_3D)
print()

1-D array :  [0.81481897 0.9628853  0.98934121 0.14290319 0.82767398]

2-D array :  [[0.27219369 0.18902501]
 [0.89101479 0.15306848]]

3-D array :  [[[0.08750274 0.51752424 0.21113455 0.38003886]
  [0.17405467 0.54056873 0.32306118 0.90631728]
  [0.6519051  0.74352033 0.350458   0.82067036]]

 [[0.41442134 0.4887786  0.60980827 0.86503246]
  [0.11013598 0.25992965 0.44621552 0.27602327]
  [0.94700775 0.24170726 0.0027649  0.48653035]]]



In [7]:
#Example of randn function

array_1D = np.random.randn(5)
print('1-D array : ',array_1D)
print()

array_2D = np.random.randn(2,2)
print('2-D array : ',array_2D)
print()
array_3D = np.random.randn(2,3,4)
print('3-D array : ',array_3D)
print()

1-D array :  [ 0.20152259 -0.03425956  0.06439461 -0.34496969 -0.03954148]

2-D array :  [[-0.61880786  0.82246101]
 [-1.54631348  1.56684557]]

3-D array :  [[[ 1.14519548 -0.52769444  1.01350239  0.72303137]
  [ 0.94081641 -0.02215317 -1.76703979 -0.54654018]
  [-0.44491143  1.67892987 -1.9490347   0.26644946]]

 [[ 1.48714689 -0.47250129  0.67811755 -0.23561834]
  [-0.55426605 -0.64192316  0.72924115 -0.17439516]
  [-0.63306107  1.08899915 -0.51702185  0.77679852]]]



In [8]:
#Example of random uniform function

array_1D = np.random.uniform(5, size = 2)
print('1-D array : ',array_1D)
print()

array_2D = np.random.uniform(2,2, size = (2,2))
print('2-D array : ',array_2D)
print()
array_3D = np.random.uniform(2,3, size =(2,3,4))
print('3-D array : ',array_3D)
print()

1-D array :  [2.32924968 4.2653726 ]

2-D array :  [[2. 2.]
 [2. 2.]]

3-D array :  [[[2.5843055  2.16381017 2.63768893 2.41477268]
  [2.9060048  2.60581512 2.91093752 2.26257972]
  [2.16592125 2.45828808 2.98483363 2.82672398]]

 [[2.75069206 2.04434468 2.37886803 2.1473847 ]
  [2.37544663 2.00396605 2.56475011 2.59504178]
  [2.29518975 2.94199066 2.63685759 2.9711069 ]]]



# Randint function
Randint function is used to print random `int` values

In [9]:
#Example of randint function

array_1D = np.random.randint(5, size = 2)
print('1-D array : ',array_1D)
print()

array_2D = np.random.randint(0,10, size = (2,2))
print('2-D array : ',array_2D)
print()
array_3D = np.random.randint(0,10, size =(2,3,4))
print('3-D array : ',array_3D)
print()

1-D array :  [3 1]

2-D array :  [[5 2]
 [7 0]]

3-D array :  [[[7 9 8 2]
  [2 2 2 1]
  [0 1 3 0]]

 [[1 2 9 0]
  [1 2 3 1]
  [0 5 0 4]]]

